version: '3.8'

services:
  web:
    build: ./star-burger
    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./star-burger:/usr/src/star-burger/
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=burgers
    ports:
      - 5432:5432

  nodejs:
    build: .star-burger/nodejs
    volumes:
      - ./star-burger/bundles-src:/usr/src/star-burger/bundles-src/
    command: ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
    depends_on:
      - web

  nginx:
    build: ./star-burger/nginx
    volumes:
      - ./star-burger/media:/media/
      - ./star-burger/staticfiles:/static/
    depends_on:
      - web
      - nodejs
    ports:
      - 1337:80

volumes:
  postgres_data: